{"errorMessage": "An error occurred (AccessDenied) when calling the StartExportTask operation: User: arn:aws:sts::253021683072:assumed-role/lambda-execution-role/export-rds-snapshot is not authorized to perform: iam:PassRole on resource: arn:aws:iam::253021683072:role/iamroles3bck because no identity-based policy allows the iam:PassRole action", "errorType": "ClientError", "stackTrace": ["  File \"/var/task/lambda_function.py\", line 22, in lambda_handler\n    rds_client.start_export_task(\n", "  File \"/var/runtime/botocore/client.py\", line 553, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/runtime/botocore/client.py\", line 1009, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]}